[tools]
rojo = { source = "Roblox/rojo-rbx-rojo", version = "=7.3.0" }
selene = { source = "Roblox/Kampfkarren-selene", version = "=0.25.0" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "=0.18.1" }
luau-lsp = { source = "JohnnyMorganz/luau-lsp", version = "=1.23.0" }
wally = { source = "UpliftGames/wally", version = "=0.3.2" }
darklua = { source = "seaofvoices/darklua", version = "=0.10.2"}
